project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: "Subprojects"
        href: subprojects.qmd
      - text: "Clusters"
        href: clusters.qmd
      - text: "Activities and Events"
        href: news.qmd

  page-footer: |
    © 2026 SFB Language between Redundancy and Deficiency
    ![](/img/logos/Logo_Graz.jpg){height=45px}
    ![](/img/logos/Salzburg_Logo.png){height=40px}
    ![](/img/logos/Uni_Wien_Logo.jpg){height=70px}
    ![](/img/logos/FWF_Logo.png){height=23px}
   

format:
  html:
    embed-resources: false
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true

echo: false
warning: false