project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - about.qmd
      - text: "TEAM"
        menu:
          - text: "SUBPROJECTS"
            href: subprojects.qmd
          - text: "CLUSTERS"
            href: clusters.qmd
      - text: "ACTIVITIES"
        href: news.qmd

  page-footer: |
    © 2026 SFB Language between Redundancy and Deficiency
    
    ![](/img/logos/Logo_Graz.jpg){height=45px}
    ![](/img/logos/Salzburg_Logo.png){height=40px}
    ![](/img/logos/Uni_Wien_Logo.jpg){height=70px}

format:
  html:
    embed-resources: false
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true

echo: false
warning: false