project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - about.qmd
      - text: "Our team"
        menu:
          - text: "Subprojects"
            href: subprojects.qmd
          - text: "Clusters"
            href: clusters.qmd
      - text: "Activities"
        href: news.qmd

format:
  html:
    embed-resources: true
    theme:
      - cosmo
      - brand
    css: styles.scss
    toc: true

brand: _brand.yml

echo: false
warning: false