---
title: "Experimental Methods Cluster"
format:
  html:
    page-layout: article
---

### Participating Projects


This cluster brings together projects 

- [**P02** - Grammatical Gender in Discourse](../subprojects/P02.qmd), 
- [**P05** - The Role of Self in Pronominal Coreference](../subprojects/P05.qmd), 
- [**P07** - Deficiency and Redundancy in Iberoromance Pronominal Systems ](../subprojects/P07.qmd), 
- [**P08** - Fading Reference - The Pragmaticalization of Pronoun + Verb](../subprojects/P08.qmd), 
- [**P09** - Animacy Features and the Flexibility of Pronouns](../subprojects/P09.qmd),  
- [**P10** - Deficiency and Redundacy in Expressing Temporal Relations](../subprojects/P10.qmd).


### Description

The Experimental Methods cluster supports the development and exchange of methodological expertise across the project network. Its activities have included a statistics workshop, a reading group, the establishment of shared infrastructure, and the exchange of practical experience in experimental work. The cluster has also organized an online workshop on conducting online experiments and has maintained close interaction with the Romance cluster. 
